Update VCS project metadata SHACL graph with `sh:group`s
regen-network/regen-registry-standards pull request #16
Opened 2022-05-09 08:33 UTC by blushi

## Description

Ref: https://github.com/regen-network/regen-registry/issues/909

Needed for front-end validation of project forms.
This is based on https://www.figma.com/file/TyhFaXqko9F8OvLEE4Zomg/Issuer-Create%2FEdit-Projects%2C-Credit-Class%2C-Batches?node-id=2%3A4449

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] manually tested (if applicable)

2022-05-09 08:40 UTC, blushi commented on shacl/projects/project-page.ttl
> +    sh:in ( "unit:HA"^^qudt:Unit "unit:AC"^^qudt:Unit ) ;
also fixed the @type value in the project metadata on the staging and production db, we were using qudt:unit (which is a property name) instead of qudt:Unit (which is the type name)

2022-05-09 10:41 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +regen:C01-ProjectShape a sh:NodeShape ;
I was thinking we could add the on-chain credit class id as prefix for the shape name.
This way we can use this iri to store this SHACL graph in the `shacl_graph` table and query a project shape based on the credit class id, as specified in the last part of https://github.com/regen-network/regen-registry/issues/909

2022-05-09 19:32 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +regen:C01-ProjectShape a sh:NodeShape ;
how would we make the query from the frontend? graphql? i guess it's pretty much "query shacl_graph by URI". seems like that should be possible from graphql...

2022-05-09 19:48 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +regen:C01-ProjectShape a sh:NodeShape ;
i do wonder about how well this approach would work for other types of credit classes. it's kind of a trivial comment but i wonder about how what the range of possibilities is for the credit class id. right now we just have C01 but maybe in the future we'll have water and biodiversity. would we try to seek a similar id for those "W01" or "BD01"? i'm just thinking if it gets more verbose than that, maybe we want to include as a property in the shacl graph?

2022-05-09 19:50 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
do we need to modify this to be `C01Project`?

2022-05-09 20:07 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +  sh:targetClass
does the fact that we have four targetClass's here mean that the following `@type` property in C01 project json could take on any of those four values? 

 https://github.com/regen-network/regen-registry-standards/blob/709a8a5382748a8dbdda761bccc1f8e4f8028d34/jsonld/projects/C01-verified-carbon-standard-project.json#L21

2022-05-09 20:10 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +    sh:path regen:previewPhoto ;
apologies if this is getting repetitive but should we also add this to the C01 project json? i'll stop commenting on these types of issues for now and wait for your feedback.

2022-05-10 06:26 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +regen:C01-ProjectShape a sh:NodeShape ;
yes we already do from such a graphql query for the old project page form from the front end: https://github.com/regen-network/regen-web/blob/master/web-registry/src/graphql/ShaclGraphByUri.graphql

2022-05-10 06:33 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +regen:C01-ProjectShape a sh:NodeShape ;
Re: your last comment, credit class ids are supposed to be short (credit type abbreviation + sequence) so I think it should be ok.
We could also specify in the graph itself the credit class but that wouldn't be helpful for querying from the front-end.

2022-05-10 06:36 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +    sh:path schema:image ;
we could do that, although as you said, this field is optional... maybe let's ask @S4mmyb what he thinks about it.

the purpose of this PR was only to come up with a proper C01 project SHACL graph in order to validate the new project forms, which is why I didn't modify the JSON template yet.

2022-05-10 06:40 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +  sh:targetClass
yes or could also be `regen:Organization` and `regen:OrganizationDisplay`
we have for different types (individual and org, normal and display) because the original project forms included one form for the entity basic info and another one for the entity display info, in case it should be displayed on the project page. Additionally the info for an individual user and an org were different.
now we just ask the same info for both and display the entity by default so I thought we could just re-use all those types.

2022-05-10 09:11 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
I was wondering about this
I think that we could actually use `regen:C01-Project` for consistency, we would need to update the @type of this project in particular: https://github.com/regen-network/regen-registry-ops/blob/cb68947a7b4416776c0fc9a8289a709f6ab53d07/C01/project-metadata/C01-ProjectId934-metadata.json

additionally we could also define that `regen:C01-Project` is a subclass of `regen:Project` (see Person/Doctor example in https://www.w3.org/TR/shacl/#targetClass): `regen:C01-Project rdfs:subClassOf regen:Project .` which brings some additional context, wdyt?

2022-05-10 09:14 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
the other thing is that ideally we would do the same for credit batches as well, ie having:
```
regen:C01-CreditBatchShape a sh:NodeShape ;
  sh:targetClass regen:C01-CreditBatch ;
```
but the thing is that we've already issued some credit batches on-chain using `regen:CreditBatch` as @type and those can't be updated...

2022-05-11 15:41 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
> additionally we could also define that regen:C01-Project is a subclass of regen:Project (see Person/Doctor example in https://www.w3.org/TR/shacl/#targetClass): regen:C01-Project rdfs:subClassOf regen:Project . which brings some additional context, wdyt?

conceptually this makes a lot of sense. and i think that could be helpful for us when we start to write the shacl schema's for new credit types (deduping things would likely be easier).

2022-05-11 15:48 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
> but the thing is that we've already issued some credit batches on-chain using regen:CreditBatch as @type and those can't be updated...

could you remind me why those can't be updated?

but that's unfortunate. maybe we just have to accept that `Project` means `C01-Project`. And maybe in the future, i.e. `regen:C02-Project` is a subclass of `regen:BaseProject` (`Project` could also be a subclass of `regen:BaseProject`)

2022-05-11 15:50 UTC, wgwz commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +    sh:path schema:image ;
I see, that makes sense. thanks for clarifying.

2022-05-12 07:18 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
agreed but as I said:

> he thing is that we've already issued some credit batches on-chain using `regen:CreditBatch` as `@type` and those can't be updated... 

which would result in inconsistencies between existing credit batches metadata and future ones...

2022-05-16 07:33 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +regen:C01-ProjectShape a sh:NodeShape ;
indeed but I still think we should have a different shape name anyway
it doesn't make sense to define multiple shapes with the same name with different properties and constraints.

2022-05-16 16:01 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
> could you remind me why those can't be updated?

credit batches are not updatable on chain

2022-05-16 21:22 UTC, S4mmyb commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +    sh:path schema:image ;
This is for the organization image, correct?

2022-05-17 00:20 UTC, S4mmyb requested changes
Hey @blushi @wgwz, thanks for the patience on my responses as I get back from the conference. I spent some time with @clevinson thinking through how we're structuring metadata for project pages and here are our thoughts. 

Generally speaking, the only information we should be storing in our on-chain metadata IRIs are information and relationships we want to query against. Right now the information and outlined in the credit class and credit batch seems pretty straight forward as most users will want to know this like, which methodology is used by a credit class or what the retirement serial number is for a certain batch. For projects it should be similar, and we should only store info want to query against, like the size or location, methodology used, start & end date, etc... 

With that in mind, things like images and videos should probably not be included in the metadata IRIs we store on chain. Obviously this adds in some complexity in the way we are currently structuring our SHACL schemas and building our project pages as we've blended much of the info we store off-chain, such as images or geojson files, query-able info we want to store on-chain, like we have [here](https://github.com/regen-network/regen-registry-ops/blob/cb68947a7b4416776c0fc9a8289a709f6ab53d07/C01/project-metadata/C01-ProjectId934-metadata.json). With that in mind, we might want to take out any non-query-able info from the `C01-verified-carbon-standard-project.ttl`, so anything in the `regen:ProjectPageMediaGroup`. 

I know this adds on some extra work (possibly outside this PR), but I think it might be best in the long run. Thoughts?

2022-05-17 07:07 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
> +    sh:path schema:image ;
yes for the project developer image for specifically (that can be individual or org)

2022-05-17 07:15 UTC, blushi commented on shacl/credit-batches/C01-verified-carbon-standard-batch.ttl
> +regen:NameOptionalUrlShape a sh:NodeShape ;
For credit batches, as it is specified currently in this SHACL schema, you need at least one additional certification but the URL for the certification is optional (you can only provide a name), which seems to be aligned with what you say

Then whether adding at least one additional certification is mandatory or not, this is just what was in the original SHACL graph that Kyle had worked on some months ago. But looking now at the figma: https://www.figma.com/file/TyhFaXqko9F8OvLEE4Zomg/Issuer-Create%2FEdit-Projects%2C-Credit-Class%2C-Batches?node-id=74%3A24702, I see that Erika made the whole field optional, thoughts?

2022-05-17 07:27 UTC, blushi commented
> Hey @blushi @wgwz, thanks for the patience on my responses as I get back from the conference. I spent some time with @clevinson thinking through how we're structuring metadata for project pages and here are our thoughts.
> 
> Generally speaking, the only information we should be storing in our on-chain metadata IRIs are information and relationships we want to query against. Right now the information and outlined in the credit class and credit batch seems pretty straight forward as most users will want to know this like, which methodology is used by a credit class or what the retirement serial number is for a certain batch. For projects it should be similar, and we should only store info want to query against, like the size or location, methodology used, start & end date, etc...
> 
> With that in mind, things like images and videos should probably not be included in the metadata IRIs we store on chain. Obviously this adds in some complexity in the way we are currently structuring our SHACL schemas and building our project pages as we've blended much of the info we store off-chain, such as images or geojson files, query-able info we want to store on-chain, like we have [here](https://github.com/regen-network/regen-registry-ops/blob/cb68947a7b4416776c0fc9a8289a709f6ab53d07/C01/project-metadata/C01-ProjectId934-metadata.json). With that in mind, we might want to take out any non-query-able info from the `C01-verified-carbon-standard-project.ttl`, so anything in the `regen:ProjectPageMediaGroup`.
> 
> I know this adds on some extra work (possibly outside this PR), but I think it might be best in the long run. Thoughts?

So just to be sure, we only want to pull out from the metadata referenced on-chain everything related to Media, right?
What about the project developer profile image? 

Right now, all the metadata is stored in the `project` table `metadata` column anyway and not referenced on-chain, so I don't believe we need to change the way things work currently.
But later on, when we have on-chain projects, we can store only "query-able" info in the `metadata_graph` table (just as we do currently for on-chain credit class/batch metadata) and keep storing the rest of the info related to media within the off-chain `project` table. This means we'll need to adapt:
- this project SHACL graph: in particular, I believe we could have one SHACL shape for C01 query-able project metadata and another one for just media data
- the way we query project data from the project page (we'll need to do this anyway once we have on-chain projects)
- the project creation form logic to save the query-able metadata in `metadata_graph` table and the rest in `project.metadata`

2022-05-17 07:36 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
Ok updated as part of https://github.com/regen-network/regen-registry-standards/pull/16/commits/4f7e38808bb918fa69605509127e2b2c59e88106 (also did the same for C01 credit batch)
this means we should indeed update the project metadata in the ops repo but also the metadata we store in the db to be consistent, should we create a separate issue to do so?

2022-05-17 07:40 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
> 



> > but the thing is that we've already issued some credit batches on-chain using regen:CreditBatch as @type and those can't be updated...
> 
> could you remind me why those can't be updated?
> 
> but that's unfortunate. maybe we just have to accept that `Project` means `C01-Project`. And maybe in the future, i.e. `regen:C02-Project` is a subclass of `regen:BaseProject` (`Project` could also be a subclass of `regen:BaseProject`)

we can edit the project metadata so I don't think that's the issue, I believe it would be confusing to just assume `regen:Project` = `regen:C01-Project` given that.
the only issue is with regards to existing credit batches metadata that we can't update on-chain but as @S4mmyb said, probably that's fine to keep those existing ones with `regen:CreditBatch` type and then have future C01 batches use `regen:C01-CreditBatch` as long as that's documented

2022-05-17 14:09 UTC, S4mmyb commented on shacl/credit-batches/C01-verified-carbon-standard-batch.ttl
> +regen:NameOptionalUrlShape a sh:NodeShape ;
Ooh cool, thanks for the explanation! And yeah I think we do want the entire field optional

2022-05-17 14:10 UTC, S4mmyb commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
> Ok updated as part of [4f7e388](https://github.com/regen-network/regen-registry-standards/commit/4f7e38808bb918fa69605509127e2b2c59e88106) (also did the same for C01 credit batch) this means we should indeed update the project metadata in the ops repo but also the metadata we store in the db to be consistent, should we create a separate issue to do so?

Yeah I think a separate issue for this makes the most sense as to not spend too much time falling down the rabbit hole on this update.

2022-05-17 14:25 UTC, S4mmyb commented
> So just to be sure, we only want to pull out from the metadata referenced on-chain everything related to Media, right? What about the project developer profile image?
> 
> Right now, all the metadata is stored in the `project` table `metadata` column anyway and not referenced on-chain, so I don't believe we need to change the way things work currently. But later on, when we have on-chain projects, we can store only "query-able" info in the `metadata_graph` table (just as we do currently for on-chain credit class/batch metadata) and keep storing the rest of the info related to media within the off-chain `project` table. This means we'll need to adapt:
> 
> * this project SHACL graph: in particular, I believe we could have one SHACL shape for C01 query-able project metadata and another one for just media data
> * the way we query project data from the project page (we'll need to do this anyway once we have on-chain projects)
> * the project creation form logic to save the query-able metadata in `metadata_graph` table and the rest in `project.metadata`

Hmm, that's a good question. I think maybe not as it's not querable and we want to stay consistent, but it would be much cleaner just to include it the way you have it so I'm split on this one. What do you think @blushi @wgwz ?

On a somewhat related note, during our retreat we talked about introducing DiDs associated with regen addresses where you could "verify" the organization or entity claiming claims against certain actions. There were some ideas circulating about anchoring a a website, twitter, or linkedin profile, to an address to provide some sort of verification of the individual/org on the other end and I'm wondering if where we would put the image in that scenario.

2022-05-18 07:22 UTC, blushi commented on shacl/credit-batches/C01-verified-carbon-standard-batch.ttl
> +regen:NameOptionalUrlShape a sh:NodeShape ;
ok made the entire field optional as part of https://github.com/regen-network/regen-registry-standards/pull/16/commits/d915b681adda69f0c3374dfc8d41b0f420d48819

2022-05-18 07:45 UTC, blushi commented on shacl/projects/C01-verified-carbon-standard-project.ttl
>    sh:targetClass regen:Project ;
added: https://github.com/regen-network/regen-registry/issues/941

2022-05-18 20:58 UTC, wgwz commented
> Hmm, that's a good question. I think maybe not as it's not querable and we want to stay consistent, but it would be much cleaner just to include it the way you have it so I'm split on this one. What do you think @blushi @wgwz ?

@S4mmyb based on what you raised in comments and how @blushi is thinking about that, I think that it makes sense to me. As I was reading Marie's comments, I was thinking that it could be helpful to have on-chain and off-chain versions of these schemas. I just wanted to propose that as a way to phrase the difference.

Also sorry for falling off on the whole C01-project discussion. I'm glad to see we've opened another issue for that. I think I'm missing some understanding on that thread but I guess we can discuss further as we handle this new task (https://github.com/regen-network/regen-registry/issues/941)

2022-05-18 21:00 UTC, wgwz approved these changes

2022-05-23 16:08 UTC, S4mmyb approved these changes

2022-05-23 16:55 UTC, wgwz commented
@S4mmyb sounds good! i'll be sure to add a topic for this.

2022-05-24 09:24 UTC, merged