feat: add C03 credit class to standards
regen-network/regen-registry-standards pull request #38
Opened 2023-01-17 16:33 UTC by wgwz

## Description

Closes: https://github.com/regen-network/regen-registry/issues/1509

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] manually tested (if applicable)

2023-01-23 17:44 UTC, clevinson approved these changes
Looks good! one question on use of `@xsd:string`

2023-01-23 17:44 UTC, clevinson commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +    }
Would it be equivalent to having all `"@xsd:string"` types just be a JSON string value instead of a wrapped object w/ nested `"@type"` & `"@value"` fields?

2023-01-23 17:44 UTC, clevinson commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +    },
ditto

2023-01-23 17:44 UTC, clevinson commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +  ],
same here

2023-01-24 03:31 UTC, S4mmyb commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +    }
yeah i messed that up and fixed it

2023-01-24 08:11 UTC, blushi requested changes

2023-01-24 08:11 UTC, blushi commented on jsonld/credit-classes/C03-Toucan-TCO2-class.jsonld
> +  "@type": "regen:CreditClass",
```suggestion
  "@type": "regen:C03-CreditClass",
```

2023-01-24 08:11 UTC, blushi commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +  {
formatting is a bit weird in this file, it should rather be for instance: 
```suggestion
  "@context": {
```

2023-01-24 14:57 UTC, wgwz commented on jsonld/credit-classes/C03-Toucan-TCO2-class.jsonld
> +  "@type": "regen:CreditClass",
we've fixed this

2023-01-24 14:57 UTC, wgwz commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +  {
we've fixed this

2023-01-24 14:58 UTC, wgwz commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +  {
note: i always just run the `./formatter.sh` script in the project root to uniformly format everything (i probably should document that at some point)

2023-01-24 14:59 UTC, wgwz commented on ops/C03/C03-Toucan-TCO2-class.jsonld
> +    },
we've fixed and simplified the credit class json-ld some more, take another look if you can @clevinson

2023-01-30 17:21 UTC, wgwz commented on ops/C03/credit-class-metadata/C03-Toucan-TCO2-class.jsonld
> +  "regen:offsetGenerationMethod": [
related: https://github.com/regen-network/regen-registry-standards/issues/35

2023-02-07 15:25 UTC, wgwz commented on ops/C03/credit-class-metadata/C03-Toucan-TCO2-class.jsonld
> +  "regen:offsetGenerationMethod": [
resolving since we're fixing this as a part of https://github.com/regen-network/regen-registry-standards/pull/37

2023-02-07 23:08 UTC, wgwz commented on shacl/credit-classes/C03-toucan-tco2-class.ttl
> +    sh:class schema:BreadcrumbList ;
note-to-self: pending https://github.com/regen-network/regen-registry-standards/pull/40 we will need to adjust this to not use `BreadcrumbList`.

2023-02-07 23:08 UTC, wgwz commented on ops/C03/credit-class-metadata/C03-Toucan-TCO2-class.jsonld
> +    "@type": "schema:BreadcrumbList",
note-to-self: pending https://github.com/regen-network/regen-registry-standards/pull/40 we will need to adjust this to not use `BreadcrumbList`.

2023-02-07 23:11 UTC, wgwz commented
note-to-self: i think it makes sense to merge this PR after these two have been merged first:
1. https://github.com/regen-network/regen-registry-standards/pull/37
2. https://github.com/regen-network/regen-registry-standards/pull/40

because of: https://github.com/regen-network/regen-registry-standards/pull/38#discussion_r1099384777

2023-03-01 16:24 UTC, blushi approved these changes

2023-03-01 16:24 UTC, merged

2023-03-01 16:24 UTC, blushi commented on ops/C03/credit-class-metadata/C03-Toucan-TCO2-class.jsonld
> +    "@type": "schema:BreadcrumbList",
let's merge as is and address this in #40