credit class metadata for fibershed credit class
regen-network/regen-registry-standards pull request #66
Opened 2023-08-15 19:57 UTC by S4mmyb

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] manually tested (if applicable)

2023-08-21 19:33 UTC, S4mmyb commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +        "schema:identifier": ""
@clevinson @ryanchristo do we want to implement some sort of identifier for regen methodologies?

2023-08-21 19:33 UTC, S4mmyb commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +        "schema:version": "***1.0",
@clevinson @ryanchristo @wgwz do we have a preference on how we want to indicate version numbers? Should we say `Version 1.0`, `v1.0`, or just `1.0`?

2023-08-21 19:39 UTC, wgwz commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +        "schema:version": "***1.0",
@S4mmyb i'd say just the number but not a strong preference on my part, i think we have this classified as just an arbitrary string in the validation rules

2023-08-21 20:05 UTC, wgwz commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +  "regen:aggregatedProjects": false,
i know we're talking about not using shacl for validating credit classes anymore, but i wanted to note in terms of shacl and where this field is specified, it's not in a common location. the field is only specified in `shacl/credit-classes/C04-ruuts-credit-class.ttl`. if we were going to maintain the shacl schema's for credit classes, then we would want to move that field into `shacl/credit-classes/credit-class.ttl`

as a side note, @clevinson i'd like to discuss this in an upcoming architecture call because i don't fully understand why we're going to direction of not maintaining the shacl for credit classes any more.

2023-08-21 20:15 UTC, wgwz reviewed
looking good to me so far!

2023-08-22 08:08 UTC, blushi requested changes

2023-08-22 08:08 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:activityDuration"
https://schema.org/activityDuration is not a type but a property, so it shouldn't be used as a type here (type names start with a capital letter as a good way to remember this)
We could just use https://schema.org/Duration instead

2023-08-22 08:08 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:frequency"
ditto schema:frequency is not a type

2023-08-22 14:06 UTC, wgwz commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:activityDuration"
just a note, unless i'm mistaken, i believe shacl validation would help us with catching these issues as well.

2023-08-22 16:21 UTC, S4mmyb commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:frequency"
yep! Thanks @blushi , this was initially drafted by Ned and I had yet to go through and fix this. I guess one question I have, and this might be helpful for @nedhorning as well, is when do we need to define things in the `@context` section and when do we not? For instance, why do we define all lists, but not elements like the `lookbackPeriod`?

2023-08-22 16:26 UTC, S4mmyb commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:activityDuration"
do we even need to define this in the context @blushi ? see my comment below

2023-08-24 08:33 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:activityDuration"
that just depends on your requirements
if you clearly want to specify that this represents a duration then this should be there

2023-08-24 08:38 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:frequency"
we define some properties as `@list` in the context in order to simplify the actual data, the 2 following JSON-LDs are exactly the same but with different formatting (compacted vs not):

```
{
  "@context": {
    "regen": "https://schema.regen.network#",
    "regen:someProperty": {
      "@container": "@list"
    }
  },
  "regen:someProperty": [
    "Element 1",
    "Element 2"
  ]
}
```

```
{
  "@context": {
    "regen": "https://schema.regen.network#"
  },
  "regen:someProperty": {
    "@list": [
      "Element 1",
      "Element 2"
    ]
  }
}
```
   

On the contrary, if your value is just a string then you don't need to specify any type, like for `lookbackPeriod`

2023-08-29 16:38 UTC, clevinson reviewed
I think we also in this PR update the generic credit-class.ttl SHACL schema to add any new fields that are both included in C05 and C04.

I wrote up a few of those here, but there are probably more fields as well.

2023-08-29 16:38 UTC, clevinson commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +      "@type": "schema:frequency"
```suggestion
      "@type": "schema:Duration"
```

I think this is what we should be using here.

2023-08-29 16:38 UTC, clevinson commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +  ],
This should also be added to the generic .ttl file

2023-08-29 22:52 UTC, S4mmyb commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +  ],
I added it to the `C05-fibershed-credit-class.ttl`, but I think we should tackle putting this into a common file in the future

2023-08-30 07:01 UTC, blushi requested changes
I guess we should rename all mentions of C05 to KSH01 in the file names

2023-08-30 07:01 UTC, blushi commented on shacl/credit-classes/C05-fibershed-credit-class.ttl
> +    sh:minCount 1 ;
`regen:creditingTerm` is currently missing in the fibershed credit class metadata, should this be optional instead?

2023-08-30 07:01 UTC, blushi commented on shacl/credit-classes/C05-fibershed-credit-class.ttl
> +    sh:minCount 1 ;
```suggestion
```

2023-08-30 07:10 UTC, blushi requested changes

2023-08-30 07:10 UTC, blushi commented on ops/C05/project-metadata/KSH01-001-project-page.jsonld
> +{
it seems like this project page metadata doesn't conform as you can see in https://github.com/regen-network/regen-registry-standards/actions/runs/6018385151/job/16326482350?pr=66

see my comments below

2023-08-30 07:10 UTC, blushi commented on ops/C05/project-metadata/KSH01-001-project-page.jsonld
> +  "schema:description": "This project, in Rutherford, CA USA will use high-density, short-duration rotational targeted sheep grazing in vineyard systems to improve ecosystem functioning through activ
this is too long, should be no longer than 600 char

2023-08-30 07:10 UTC, blushi commented on ops/C05/project-metadata/KSH01-001-project-page.jsonld
> +  },
```suggestion
```

2023-08-30 07:10 UTC, blushi commented on ops/C05/project-metadata/KSH01-001-project-page.jsonld
> +      "schema:caption": "",
```suggestion
```

2023-08-30 07:10 UTC, blushi commented on ops/C05/project-metadata/KSH01-001-project-page.jsonld
> +      "schema:caption": "",
```suggestion
```

2023-08-30 07:10 UTC, blushi commented on ops/C05/project-metadata/KSH01-001-project-page.jsonld
> +      "schema:caption": "",
```suggestion
```

2023-08-30 16:08 UTC, S4mmyb commented on jsonld/projects/C05-project.jsonld
> +      "schema:url": "regen187d6u5ypmhdc2ypwfwt2ye6d424a0cjvxw72gu"
that makes sense - this is the one ned originally created and I forgot to edit this one as I was mostly focusing on the project file in the ops folder. Given that project developer / verifier is something we fill out in the UI I don't think this needs to be anchored on-chain so I'm removing it

2023-08-30 16:11 UTC, S4mmyb commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +  "regen:projectBenefits": [
this was defined in the context as `regen:coBenefits` so I changed it to `regen:projectBenefits`

2023-08-30 16:23 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +  "regen:projectBenefits": [
so they are not measured, right?
this is the proposal for defining measured co-benefits vs project benefits: https://github.com/regen-network/regen-registry-standards/pull/64/files#diff-f0ae3d2e23dcce8615b90d590b233addb605a726d96153c815120ba2e37bb14a
and this is what the front-end will supports, unless you have other options.

2023-08-30 16:46 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +    "regen:projectBenefits": {
```suggestion
    "regen:coBenefits": {

```

2023-08-30 16:46 UTC, blushi commented on ops/C05/credit-class-metadata/C05_fibershed_credit_class.jsonld
> +  ],
```suggestion
  "regen:coBenefits": [
    {
      "@id": "regen:ImprovedRatesOfNutrientCycling",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Improved rates of nutrient cycling"
    },
    {
      "@id": "regen:ImprovedNutrientRetention",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Improved nutrient retention"
    },
    {
      "@id": "regen:ReductionsInExternalInputs",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Reductions in external inputs"
    },
    {
      "@id": "regen:ReductionsInExternalInputs",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Reductions in external inputs"
    },
    {
      "@id": "regen:IncreasedSoilMicrobialBiomass",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Increased soil microbial biomass"
    },
    {
      "@id": "regen:ImprovedSoilStructureAndHydrologicalProperties",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Improved soil structure and hydrological properties"
    },
    {
      "@id": "regen:IncreasedSoilCarbonStorage",
      "@type": "regen:ProjectBenefit",
      "schema:name": "Increased soil carbon storage"
    }
  ],

```

2023-08-30 17:09 UTC, blushi commented on shacl/credit-classes/KSH01-fibershed-credit-class.ttl
> +  ] ;
```suggestion
```

2023-08-30 18:20 UTC, blushi approved these changes

2023-08-30 18:20 UTC, blushi commented on ops/KSH01/credit-class-metadata/KSH01_fibershed_credit_class.jsonld
> +    },
```suggestion
```

2023-09-06 03:03 UTC, wgwz commented
@blushi i was just looking at the ci check for this PR and it looks like we might have some field in the common credit class file that needs to marked as optional? not 100% sure that's what's going on but just wanted to flag it.
```
shapes=/tmp/tmpkh85egq6.ttl data=jsonld/C03/project-metadata/C03-project-full-example.jsonld result=ERROR
org.apache.jena.shacl.parser.ShaclParseException: Missing property shape: node=_:Bf57badc002b17e27a20492cee90c4874 sh:property <[https://schema.regen.network#creditGenerationMethodPropertyShape](https://schema.regen.network/#creditGenerationMethodPropertyShape)>
```

2023-09-06 07:09 UTC, blushi commented
> @blushi i was just looking at the ci check for this PR and it looks like we might have some field in the common credit class file that needs to marked as optional? not 100% sure that's what's going on but just wanted to flag it.
> 
> ```
> shapes=/tmp/tmpkh85egq6.ttl data=jsonld/C03/project-metadata/C03-project-full-example.jsonld result=ERROR
> org.apache.jena.shacl.parser.ShaclParseException: Missing property shape: node=_:Bf57badc002b17e27a20492cee90c4874 sh:property <[https://schema.regen.network#creditGenerationMethodPropertyShape](https://schema.regen.network/#creditGenerationMethodPropertyShape)>
> ```

There's a follow-up issue about moving properties to the generic credit class ttl and making some of them optional: https://github.com/regen-network/regen-registry-standards/issues/70
In the mean time, I fixed the missing property issue (just a typo).

2023-11-06 22:45 UTC, closed without merging